name: Test for inputs.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '環境を選択してください'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "selected environment is [" ${{ inputs.environment }} "] ."
      - name: Dev環境向け
        if: ${{ inputs.environment == ''dev }}
        run: echo 'build for dev.'
      - name: Stg環境向け
        if: ${{ inputs.environment == 'stg' }}
        run: echo 'build for stg.'
      - name: Prd環境向け
        if: ${{ inputs.environment == 'prd' }}
        run: echo 'build for prd.'
